create view if not exists "pay.t_auth_log"(
ROWKEY varchar primary key, 
"info"."log_id" varchar,
"info"."status" varchar,
"info"."notify_status" varchar,
"info"."notify_url" varchar,
"info"."create_time" varchar,
"info"."auth_type" varchar,
"info"."auth_product" varchar,
"info"."real_name" varchar,
"info"."idcard_no" varchar,
"info"."bank_code" varchar,
"info"."bank_no" varchar,
"info"."bank_name" varchar,
"info"."mobile" varchar,
"info"."user_id" varchar,
"info"."record_id" varchar,
"info"."result_code" varchar,
"info"."result_desc" varchar,
"info"."chan_id" varchar,
"info"."channel_no" varchar,
"info"."trans_id" varchar,
"info"."bus_req_id" varchar,
"info"."province_name" varchar,
"info"."province_code" varchar,
"info"."city_name" varchar,
"info"."city_code" varchar
);
create view if not exists "pay.t_auth_record"(
ROWKEY varchar primary key, 
"info"."record_id" varchar,
"info"."status" varchar,
"info"."notify_status" varchar,
"info"."notify_url" varchar,
"info"."result_code" varchar,
"info"."result_desc" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar,
"info"."auth_type" varchar,
"info"."auth_product" varchar,
"info"."real_name" varchar,
"info"."idcard_no" varchar,
"info"."bank_code" varchar,
"info"."bank_no" varchar,
"info"."bank_name" varchar,
"info"."mobile" varchar,
"info"."user_id" varchar,
"info"."disable" varchar,
"info"."chan_id" varchar,
"info"."channel_no" varchar,
"info"."trans_id" varchar,
"info"."bus_req_id" varchar,
"info"."province_name" varchar,
"info"."province_code" varchar,
"info"."city_name" varchar,
"info"."city_code" varchar
);
create view if not exists "pay.t_channel_info"(
ROWKEY varchar primary key, 
"info"."channel_no" varchar,
"info"."channel_code" varchar,
"info"."channel_name" varchar,
"info"."valid" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar,
"info"."data" varchar
);
create view if not exists "pay.t_pay_chan"(
ROWKEY varchar primary key, 
"info"."chan_id" varchar,
"info"."chan_name" varchar,
"info"."chan_service" varchar,
"info"."valid" varchar,
"info"."product_type" varchar,
"info"."creator" varchar,
"info"."editor" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar,
"info"."remark" varchar,
"info"."channel_no" varchar
);
create view if not exists "pay.t_recharge_ledger"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."sn" varchar,
"info"."merchant_id" varchar,
"info"."amount" varchar,
"info"."record_id" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar
);
create view if not exists "pay.t_recharge_log"(
ROWKEY varchar primary key, 
"info"."log_id" varchar,
"info"."amount" varchar,
"info"."finsh_time" varchar,
"info"."status" varchar,
"info"."notify_status" varchar,
"info"."currency" varchar,
"info"."nofity_url" varchar,
"info"."result_code" varchar,
"info"."result_desc" varchar,
"info"."create_time" varchar,
"info"."bus_req_id" varchar,
"info"."user_id" varchar,
"info"."record_id" varchar,
"info"."card_no" varchar,
"info"."pay_type" varchar,
"info"."card_type" varchar,
"info"."settle_date" varchar,
"info"."chan_order_id" varchar,
"info"."trans_id" varchar,
"info"."chan_id" varchar,
"info"."channel_no" varchar,
"info"."pay_src" varchar,
"info"."timer" varchar,
"info"."remark" varchar,
"info"."creator" varchar,
"info"."editor" varchar
);
create view if not exists "pay.t_recharge_order"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."record_id" varchar,
"info"."order_id" varchar,
"info"."repayment_id" varchar,
"info"."phase" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar
);
create view if not exists "pay.t_recharge_record"(
ROWKEY varchar primary key, 
"info"."record_id" varchar,
"info"."amount" varchar,
"info"."finsh_time" varchar,
"info"."status" varchar,
"info"."notify_status" varchar,
"info"."currency" varchar,
"info"."nofity_url" varchar,
"info"."chan_order_id" varchar,
"info"."result_code" varchar,
"info"."result_desc" varchar,
"info"."create_time" varchar,
"info"."bus_req_id" varchar,
"info"."user_id" varchar,
"info"."disable" varchar,
"info"."card_no" varchar,
"info"."pay_type" varchar,
"info"."edit_time" varchar,
"info"."card_type" varchar,
"info"."settle_date" varchar,
"info"."trans_id" varchar,
"info"."chan_id" varchar,
"info"."channel_no" varchar,
"info"."pay_src" varchar,
"info"."timer" varchar,
"info"."remark" varchar,
"info"."creator" varchar,
"info"."editor" varchar
);
