create view if not exists "mobile.t_app_ref_channel"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."ref_id" varchar,
"info"."ref_type" varchar,
"info"."channel_code" varchar,
"info"."channel_name" varchar,
"info"."channel_type" varchar
);
create view if not exists "mobile.t_app_release"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."name" varchar,
"info"."title" varchar,
"info"."version" varchar,
"info"."size" varchar,
"info"."url" varchar,
"info"."file_id" varchar,
"info"."remarks" varchar,
"info"."status" varchar,
"info"."update_time" varchar,
"info"."update_user" varchar,
"info"."create_time" varchar,
"info"."create_user" varchar
);
create view if not exists "mobile.t_app_rn_version"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."os_type" varchar,
"info"."title" varchar,
"info"."content" varchar,
"info"."update_channel" varchar,
"info"."update_method" varchar,
"info"."file_id" varchar,
"info"."url" varchar,
"info"."min_update_version" varchar,
"info"."create_time" varchar,
"info"."create_user" varchar,
"info"."update_user" varchar,
"info"."update_time" varchar,
"info"."status" varchar,
"info"."version" varchar,
"info"."next_popup_time" varchar,
"info"."version_number" varchar,
"info"."md5" varchar,
"info"."start_time" varchar,
"info"."end_time" varchar,
"info"."min_update_version_number" varchar
);
create view if not exists "mobile.t_app_splash_screen"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."os_type" varchar,
"info"."channel_dim" varchar,
"info"."name" varchar,
"info"."skip_url" varchar,
"info"."start_time" varchar,
"info"."end_time" varchar,
"info"."status" varchar,
"info"."remarks" varchar,
"info"."sort" varchar,
"info"."update_time" varchar,
"info"."update_user" varchar,
"info"."create_time" varchar,
"info"."create_user" varchar,
"info"."show_time" varchar
);
create view if not exists "mobile.t_app_splash_screen_img"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."splash_screen_id" varchar,
"info"."file_id" varchar,
"info"."img_type" varchar,
"info"."img_url" varchar,
"info"."status" varchar,
"info"."update_time" varchar,
"info"."create_time" varchar,
"info"."update_user" varchar,
"info"."create_user" varchar
);
create view if not exists "mobile.t_app_version_update"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."os_type" varchar,
"info"."title" varchar,
"info"."content" varchar,
"info"."update_channel" varchar,
"info"."update_method" varchar,
"info"."file_id" varchar,
"info"."url" varchar,
"info"."min_update_version" varchar,
"info"."create_time" varchar,
"info"."create_user" varchar,
"info"."update_user" varchar,
"info"."update_time" varchar,
"info"."status" varchar,
"info"."version" varchar,
"info"."next_popup_time" varchar,
"info"."version_number" varchar,
"info"."md5" varchar,
"info"."start_time" varchar,
"info"."end_time" varchar,
"info"."min_update_version_number" varchar
);
