create view if not exists "performance_schema.accounts"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."HOST" varchar,
"info"."CURRENT_CONNECTIONS" varchar,
"info"."TOTAL_CONNECTIONS" varchar
);
create view if not exists "performance_schema.cond_instances"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar
);
create view if not exists "performance_schema.events_stages_current"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_stages_history"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_stages_history_long"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_stages_summary_by_account_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_stages_summary_by_host_by_event_name"(
ROWKEY varchar primary key, 
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_stages_summary_by_thread_by_event_name"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_stages_summary_by_user_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_stages_summary_global_by_event_name"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_statements_current"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."LOCK_TIME" varchar,
"info"."SQL_TEXT" varchar,
"info"."DIGEST" varchar,
"info"."DIGEST_TEXT" varchar,
"info"."CURRENT_SCHEMA" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."MYSQL_ERRNO" varchar,
"info"."RETURNED_SQLSTATE" varchar,
"info"."MESSAGE_TEXT" varchar,
"info"."ERRORS" varchar,
"info"."WARNINGS" varchar,
"info"."ROWS_AFFECTED" varchar,
"info"."ROWS_SENT" varchar,
"info"."ROWS_EXAMINED" varchar,
"info"."CREATED_TMP_DISK_TABLES" varchar,
"info"."CREATED_TMP_TABLES" varchar,
"info"."SELECT_FULL_JOIN" varchar,
"info"."SELECT_FULL_RANGE_JOIN" varchar,
"info"."SELECT_RANGE" varchar,
"info"."SELECT_RANGE_CHECK" varchar,
"info"."SELECT_SCAN" varchar,
"info"."SORT_MERGE_PASSES" varchar,
"info"."SORT_RANGE" varchar,
"info"."SORT_ROWS" varchar,
"info"."SORT_SCAN" varchar,
"info"."NO_INDEX_USED" varchar,
"info"."NO_GOOD_INDEX_USED" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_statements_history"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."LOCK_TIME" varchar,
"info"."SQL_TEXT" varchar,
"info"."DIGEST" varchar,
"info"."DIGEST_TEXT" varchar,
"info"."CURRENT_SCHEMA" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."MYSQL_ERRNO" varchar,
"info"."RETURNED_SQLSTATE" varchar,
"info"."MESSAGE_TEXT" varchar,
"info"."ERRORS" varchar,
"info"."WARNINGS" varchar,
"info"."ROWS_AFFECTED" varchar,
"info"."ROWS_SENT" varchar,
"info"."ROWS_EXAMINED" varchar,
"info"."CREATED_TMP_DISK_TABLES" varchar,
"info"."CREATED_TMP_TABLES" varchar,
"info"."SELECT_FULL_JOIN" varchar,
"info"."SELECT_FULL_RANGE_JOIN" varchar,
"info"."SELECT_RANGE" varchar,
"info"."SELECT_RANGE_CHECK" varchar,
"info"."SELECT_SCAN" varchar,
"info"."SORT_MERGE_PASSES" varchar,
"info"."SORT_RANGE" varchar,
"info"."SORT_ROWS" varchar,
"info"."SORT_SCAN" varchar,
"info"."NO_INDEX_USED" varchar,
"info"."NO_GOOD_INDEX_USED" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_statements_history_long"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."LOCK_TIME" varchar,
"info"."SQL_TEXT" varchar,
"info"."DIGEST" varchar,
"info"."DIGEST_TEXT" varchar,
"info"."CURRENT_SCHEMA" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."MYSQL_ERRNO" varchar,
"info"."RETURNED_SQLSTATE" varchar,
"info"."MESSAGE_TEXT" varchar,
"info"."ERRORS" varchar,
"info"."WARNINGS" varchar,
"info"."ROWS_AFFECTED" varchar,
"info"."ROWS_SENT" varchar,
"info"."ROWS_EXAMINED" varchar,
"info"."CREATED_TMP_DISK_TABLES" varchar,
"info"."CREATED_TMP_TABLES" varchar,
"info"."SELECT_FULL_JOIN" varchar,
"info"."SELECT_FULL_RANGE_JOIN" varchar,
"info"."SELECT_RANGE" varchar,
"info"."SELECT_RANGE_CHECK" varchar,
"info"."SELECT_SCAN" varchar,
"info"."SORT_MERGE_PASSES" varchar,
"info"."SORT_RANGE" varchar,
"info"."SORT_ROWS" varchar,
"info"."SORT_SCAN" varchar,
"info"."NO_INDEX_USED" varchar,
"info"."NO_GOOD_INDEX_USED" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar
);
create view if not exists "performance_schema.events_statements_summary_by_account_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar
);
create view if not exists "performance_schema.events_statements_summary_by_digest"(
ROWKEY varchar primary key, 
"info"."SCHEMA_NAME" varchar,
"info"."DIGEST" varchar,
"info"."DIGEST_TEXT" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar,
"info"."FIRST_SEEN" varchar,
"info"."LAST_SEEN" varchar
);
create view if not exists "performance_schema.events_statements_summary_by_host_by_event_name"(
ROWKEY varchar primary key, 
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar
);
create view if not exists "performance_schema.events_statements_summary_by_thread_by_event_name"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar
);
create view if not exists "performance_schema.events_statements_summary_by_user_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar
);
create view if not exists "performance_schema.events_statements_summary_global_by_event_name"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."SUM_LOCK_TIME" varchar,
"info"."SUM_ERRORS" varchar,
"info"."SUM_WARNINGS" varchar,
"info"."SUM_ROWS_AFFECTED" varchar,
"info"."SUM_ROWS_SENT" varchar,
"info"."SUM_ROWS_EXAMINED" varchar,
"info"."SUM_CREATED_TMP_DISK_TABLES" varchar,
"info"."SUM_CREATED_TMP_TABLES" varchar,
"info"."SUM_SELECT_FULL_JOIN" varchar,
"info"."SUM_SELECT_FULL_RANGE_JOIN" varchar,
"info"."SUM_SELECT_RANGE" varchar,
"info"."SUM_SELECT_RANGE_CHECK" varchar,
"info"."SUM_SELECT_SCAN" varchar,
"info"."SUM_SORT_MERGE_PASSES" varchar,
"info"."SUM_SORT_RANGE" varchar,
"info"."SUM_SORT_ROWS" varchar,
"info"."SUM_SORT_SCAN" varchar,
"info"."SUM_NO_INDEX_USED" varchar,
"info"."SUM_NO_GOOD_INDEX_USED" varchar
);
create view if not exists "performance_schema.events_waits_current"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."SPINS" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."INDEX_NAME" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar,
"info"."OPERATION" varchar,
"info"."NUMBER_OF_BYTES" varchar,
"info"."FLAGS" varchar
);
create view if not exists "performance_schema.events_waits_history"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."SPINS" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."INDEX_NAME" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar,
"info"."OPERATION" varchar,
"info"."NUMBER_OF_BYTES" varchar,
"info"."FLAGS" varchar
);
create view if not exists "performance_schema.events_waits_history_long"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_ID" varchar,
"info"."END_EVENT_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."SOURCE" varchar,
"info"."TIMER_START" varchar,
"info"."TIMER_END" varchar,
"info"."TIMER_WAIT" varchar,
"info"."SPINS" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."INDEX_NAME" varchar,
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."NESTING_EVENT_ID" varchar,
"info"."NESTING_EVENT_TYPE" varchar,
"info"."OPERATION" varchar,
"info"."NUMBER_OF_BYTES" varchar,
"info"."FLAGS" varchar
);
create view if not exists "performance_schema.events_waits_summary_by_account_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_waits_summary_by_host_by_event_name"(
ROWKEY varchar primary key, 
"info"."HOST" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_waits_summary_by_instance"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_waits_summary_by_thread_by_event_name"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_waits_summary_by_user_by_event_name"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.events_waits_summary_global_by_event_name"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.file_instances"(
ROWKEY varchar primary key, 
"info"."FILE_NAME" varchar,
"info"."EVENT_NAME" varchar,
"info"."OPEN_COUNT" varchar
);
create view if not exists "performance_schema.file_summary_by_event_name"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."SUM_NUMBER_OF_BYTES_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."SUM_NUMBER_OF_BYTES_WRITE" varchar,
"info"."COUNT_MISC" varchar,
"info"."SUM_TIMER_MISC" varchar,
"info"."MIN_TIMER_MISC" varchar,
"info"."AVG_TIMER_MISC" varchar,
"info"."MAX_TIMER_MISC" varchar
);
create view if not exists "performance_schema.file_summary_by_instance"(
ROWKEY varchar primary key, 
"info"."FILE_NAME" varchar,
"info"."EVENT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."SUM_NUMBER_OF_BYTES_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."SUM_NUMBER_OF_BYTES_WRITE" varchar,
"info"."COUNT_MISC" varchar,
"info"."SUM_TIMER_MISC" varchar,
"info"."MIN_TIMER_MISC" varchar,
"info"."AVG_TIMER_MISC" varchar,
"info"."MAX_TIMER_MISC" varchar
);
create view if not exists "performance_schema.host_cache"(
ROWKEY varchar primary key, 
"info"."IP" varchar,
"info"."HOST" varchar,
"info"."HOST_VALIDATED" varchar,
"info"."SUM_CONNECT_ERRORS" varchar,
"info"."COUNT_HOST_BLOCKED_ERRORS" varchar,
"info"."COUNT_NAMEINFO_TRANSIENT_ERRORS" varchar,
"info"."COUNT_NAMEINFO_PERMANENT_ERRORS" varchar,
"info"."COUNT_FORMAT_ERRORS" varchar,
"info"."COUNT_ADDRINFO_TRANSIENT_ERRORS" varchar,
"info"."COUNT_ADDRINFO_PERMANENT_ERRORS" varchar,
"info"."COUNT_FCRDNS_ERRORS" varchar,
"info"."COUNT_HOST_ACL_ERRORS" varchar,
"info"."COUNT_NO_AUTH_PLUGIN_ERRORS" varchar,
"info"."COUNT_AUTH_PLUGIN_ERRORS" varchar,
"info"."COUNT_HANDSHAKE_ERRORS" varchar,
"info"."COUNT_PROXY_USER_ERRORS" varchar,
"info"."COUNT_PROXY_USER_ACL_ERRORS" varchar,
"info"."COUNT_AUTHENTICATION_ERRORS" varchar,
"info"."COUNT_SSL_ERRORS" varchar,
"info"."COUNT_MAX_USER_CONNECTIONS_ERRORS" varchar,
"info"."COUNT_MAX_USER_CONNECTIONS_PER_HOUR_ERRORS" varchar,
"info"."COUNT_DEFAULT_DATABASE_ERRORS" varchar,
"info"."COUNT_INIT_CONNECT_ERRORS" varchar,
"info"."COUNT_LOCAL_ERRORS" varchar,
"info"."COUNT_UNKNOWN_ERRORS" varchar,
"info"."FIRST_SEEN" varchar,
"info"."LAST_SEEN" varchar,
"info"."FIRST_ERROR_SEEN" varchar,
"info"."LAST_ERROR_SEEN" varchar
);
create view if not exists "performance_schema.hosts"(
ROWKEY varchar primary key, 
"info"."HOST" varchar,
"info"."CURRENT_CONNECTIONS" varchar,
"info"."TOTAL_CONNECTIONS" varchar
);
create view if not exists "performance_schema.mutex_instances"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."LOCKED_BY_THREAD_ID" varchar
);
create view if not exists "performance_schema.objects_summary_global_by_type"(
ROWKEY varchar primary key, 
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar
);
create view if not exists "performance_schema.performance_timers"(
ROWKEY varchar primary key, 
"info"."TIMER_NAME" varchar,
"info"."TIMER_FREQUENCY" varchar,
"info"."TIMER_RESOLUTION" varchar,
"info"."TIMER_OVERHEAD" varchar
);
create view if not exists "performance_schema.rwlock_instances"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."WRITE_LOCKED_BY_THREAD_ID" varchar,
"info"."READ_LOCKED_BY_COUNT" varchar
);
create view if not exists "performance_schema.session_account_connect_attrs"(
ROWKEY varchar primary key, 
"info"."PROCESSLIST_ID" varchar,
"info"."ATTR_NAME" varchar,
"info"."ATTR_VALUE" varchar,
"info"."ORDINAL_POSITION" varchar
);
create view if not exists "performance_schema.session_connect_attrs"(
ROWKEY varchar primary key, 
"info"."PROCESSLIST_ID" varchar,
"info"."ATTR_NAME" varchar,
"info"."ATTR_VALUE" varchar,
"info"."ORDINAL_POSITION" varchar
);
create view if not exists "performance_schema.setup_actors"(
ROWKEY varchar primary key, 
"info"."HOST" varchar,
"info"."USER" varchar,
"info"."ROLE" varchar
);
create view if not exists "performance_schema.setup_consumers"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."ENABLED" varchar
);
create view if not exists "performance_schema.setup_instruments"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."ENABLED" varchar,
"info"."TIMED" varchar
);
create view if not exists "performance_schema.setup_objects"(
ROWKEY varchar primary key, 
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."ENABLED" varchar,
"info"."TIMED" varchar
);
create view if not exists "performance_schema.setup_timers"(
ROWKEY varchar primary key, 
"info"."NAME" varchar,
"info"."TIMER_NAME" varchar
);
create view if not exists "performance_schema.socket_instances"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."THREAD_ID" varchar,
"info"."SOCKET_ID" varchar,
"info"."IP" varchar,
"info"."PORT" varchar,
"info"."STATE" varchar
);
create view if not exists "performance_schema.socket_summary_by_event_name"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."SUM_NUMBER_OF_BYTES_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."SUM_NUMBER_OF_BYTES_WRITE" varchar,
"info"."COUNT_MISC" varchar,
"info"."SUM_TIMER_MISC" varchar,
"info"."MIN_TIMER_MISC" varchar,
"info"."AVG_TIMER_MISC" varchar,
"info"."MAX_TIMER_MISC" varchar
);
create view if not exists "performance_schema.socket_summary_by_instance"(
ROWKEY varchar primary key, 
"info"."EVENT_NAME" varchar,
"info"."OBJECT_INSTANCE_BEGIN" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."SUM_NUMBER_OF_BYTES_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."SUM_NUMBER_OF_BYTES_WRITE" varchar,
"info"."COUNT_MISC" varchar,
"info"."SUM_TIMER_MISC" varchar,
"info"."MIN_TIMER_MISC" varchar,
"info"."AVG_TIMER_MISC" varchar,
"info"."MAX_TIMER_MISC" varchar
);
create view if not exists "performance_schema.table_io_waits_summary_by_index_usage"(
ROWKEY varchar primary key, 
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."INDEX_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."COUNT_FETCH" varchar,
"info"."SUM_TIMER_FETCH" varchar,
"info"."MIN_TIMER_FETCH" varchar,
"info"."AVG_TIMER_FETCH" varchar,
"info"."MAX_TIMER_FETCH" varchar,
"info"."COUNT_INSERT" varchar,
"info"."SUM_TIMER_INSERT" varchar,
"info"."MIN_TIMER_INSERT" varchar,
"info"."AVG_TIMER_INSERT" varchar,
"info"."MAX_TIMER_INSERT" varchar,
"info"."COUNT_UPDATE" varchar,
"info"."SUM_TIMER_UPDATE" varchar,
"info"."MIN_TIMER_UPDATE" varchar,
"info"."AVG_TIMER_UPDATE" varchar,
"info"."MAX_TIMER_UPDATE" varchar,
"info"."COUNT_DELETE" varchar,
"info"."SUM_TIMER_DELETE" varchar,
"info"."MIN_TIMER_DELETE" varchar,
"info"."AVG_TIMER_DELETE" varchar,
"info"."MAX_TIMER_DELETE" varchar
);
create view if not exists "performance_schema.table_io_waits_summary_by_table"(
ROWKEY varchar primary key, 
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."COUNT_FETCH" varchar,
"info"."SUM_TIMER_FETCH" varchar,
"info"."MIN_TIMER_FETCH" varchar,
"info"."AVG_TIMER_FETCH" varchar,
"info"."MAX_TIMER_FETCH" varchar,
"info"."COUNT_INSERT" varchar,
"info"."SUM_TIMER_INSERT" varchar,
"info"."MIN_TIMER_INSERT" varchar,
"info"."AVG_TIMER_INSERT" varchar,
"info"."MAX_TIMER_INSERT" varchar,
"info"."COUNT_UPDATE" varchar,
"info"."SUM_TIMER_UPDATE" varchar,
"info"."MIN_TIMER_UPDATE" varchar,
"info"."AVG_TIMER_UPDATE" varchar,
"info"."MAX_TIMER_UPDATE" varchar,
"info"."COUNT_DELETE" varchar,
"info"."SUM_TIMER_DELETE" varchar,
"info"."MIN_TIMER_DELETE" varchar,
"info"."AVG_TIMER_DELETE" varchar,
"info"."MAX_TIMER_DELETE" varchar
);
create view if not exists "performance_schema.table_lock_waits_summary_by_table"(
ROWKEY varchar primary key, 
"info"."OBJECT_TYPE" varchar,
"info"."OBJECT_SCHEMA" varchar,
"info"."OBJECT_NAME" varchar,
"info"."COUNT_STAR" varchar,
"info"."SUM_TIMER_WAIT" varchar,
"info"."MIN_TIMER_WAIT" varchar,
"info"."AVG_TIMER_WAIT" varchar,
"info"."MAX_TIMER_WAIT" varchar,
"info"."COUNT_READ" varchar,
"info"."SUM_TIMER_READ" varchar,
"info"."MIN_TIMER_READ" varchar,
"info"."AVG_TIMER_READ" varchar,
"info"."MAX_TIMER_READ" varchar,
"info"."COUNT_WRITE" varchar,
"info"."SUM_TIMER_WRITE" varchar,
"info"."MIN_TIMER_WRITE" varchar,
"info"."AVG_TIMER_WRITE" varchar,
"info"."MAX_TIMER_WRITE" varchar,
"info"."COUNT_READ_NORMAL" varchar,
"info"."SUM_TIMER_READ_NORMAL" varchar,
"info"."MIN_TIMER_READ_NORMAL" varchar,
"info"."AVG_TIMER_READ_NORMAL" varchar,
"info"."MAX_TIMER_READ_NORMAL" varchar,
"info"."COUNT_READ_WITH_SHARED_LOCKS" varchar,
"info"."SUM_TIMER_READ_WITH_SHARED_LOCKS" varchar,
"info"."MIN_TIMER_READ_WITH_SHARED_LOCKS" varchar,
"info"."AVG_TIMER_READ_WITH_SHARED_LOCKS" varchar,
"info"."MAX_TIMER_READ_WITH_SHARED_LOCKS" varchar,
"info"."COUNT_READ_HIGH_PRIORITY" varchar,
"info"."SUM_TIMER_READ_HIGH_PRIORITY" varchar,
"info"."MIN_TIMER_READ_HIGH_PRIORITY" varchar,
"info"."AVG_TIMER_READ_HIGH_PRIORITY" varchar,
"info"."MAX_TIMER_READ_HIGH_PRIORITY" varchar,
"info"."COUNT_READ_NO_INSERT" varchar,
"info"."SUM_TIMER_READ_NO_INSERT" varchar,
"info"."MIN_TIMER_READ_NO_INSERT" varchar,
"info"."AVG_TIMER_READ_NO_INSERT" varchar,
"info"."MAX_TIMER_READ_NO_INSERT" varchar,
"info"."COUNT_READ_EXTERNAL" varchar,
"info"."SUM_TIMER_READ_EXTERNAL" varchar,
"info"."MIN_TIMER_READ_EXTERNAL" varchar,
"info"."AVG_TIMER_READ_EXTERNAL" varchar,
"info"."MAX_TIMER_READ_EXTERNAL" varchar,
"info"."COUNT_WRITE_ALLOW_WRITE" varchar,
"info"."SUM_TIMER_WRITE_ALLOW_WRITE" varchar,
"info"."MIN_TIMER_WRITE_ALLOW_WRITE" varchar,
"info"."AVG_TIMER_WRITE_ALLOW_WRITE" varchar,
"info"."MAX_TIMER_WRITE_ALLOW_WRITE" varchar,
"info"."COUNT_WRITE_CONCURRENT_INSERT" varchar,
"info"."SUM_TIMER_WRITE_CONCURRENT_INSERT" varchar,
"info"."MIN_TIMER_WRITE_CONCURRENT_INSERT" varchar,
"info"."AVG_TIMER_WRITE_CONCURRENT_INSERT" varchar,
"info"."MAX_TIMER_WRITE_CONCURRENT_INSERT" varchar,
"info"."COUNT_WRITE_DELAYED" varchar,
"info"."SUM_TIMER_WRITE_DELAYED" varchar,
"info"."MIN_TIMER_WRITE_DELAYED" varchar,
"info"."AVG_TIMER_WRITE_DELAYED" varchar,
"info"."MAX_TIMER_WRITE_DELAYED" varchar,
"info"."COUNT_WRITE_LOW_PRIORITY" varchar,
"info"."SUM_TIMER_WRITE_LOW_PRIORITY" varchar,
"info"."MIN_TIMER_WRITE_LOW_PRIORITY" varchar,
"info"."AVG_TIMER_WRITE_LOW_PRIORITY" varchar,
"info"."MAX_TIMER_WRITE_LOW_PRIORITY" varchar,
"info"."COUNT_WRITE_NORMAL" varchar,
"info"."SUM_TIMER_WRITE_NORMAL" varchar,
"info"."MIN_TIMER_WRITE_NORMAL" varchar,
"info"."AVG_TIMER_WRITE_NORMAL" varchar,
"info"."MAX_TIMER_WRITE_NORMAL" varchar,
"info"."COUNT_WRITE_EXTERNAL" varchar,
"info"."SUM_TIMER_WRITE_EXTERNAL" varchar,
"info"."MIN_TIMER_WRITE_EXTERNAL" varchar,
"info"."AVG_TIMER_WRITE_EXTERNAL" varchar,
"info"."MAX_TIMER_WRITE_EXTERNAL" varchar
);
create view if not exists "performance_schema.threads"(
ROWKEY varchar primary key, 
"info"."THREAD_ID" varchar,
"info"."NAME" varchar,
"info"."TYPE" varchar,
"info"."PROCESSLIST_ID" varchar,
"info"."PROCESSLIST_USER" varchar,
"info"."PROCESSLIST_HOST" varchar,
"info"."PROCESSLIST_DB" varchar,
"info"."PROCESSLIST_COMMAND" varchar,
"info"."PROCESSLIST_TIME" varchar,
"info"."PROCESSLIST_STATE" varchar,
"info"."PROCESSLIST_INFO" varchar,
"info"."PARENT_THREAD_ID" varchar,
"info"."ROLE" varchar,
"info"."INSTRUMENTED" varchar
);
create view if not exists "performance_schema.users"(
ROWKEY varchar primary key, 
"info"."USER" varchar,
"info"."CURRENT_CONNECTIONS" varchar,
"info"."TOTAL_CONNECTIONS" varchar
);
