create view if not exists "order.t_order_attr"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."order_id" varchar,
"info"."user_id" varchar,
"info"."attr_key" varchar,
"info"."key_name" varchar,
"info"."attr_value" varchar,
"info"."section_id" varchar,
"info"."section_name" varchar,
"info"."create_time" varchar,
"info"."remark" varchar
);
create view if not exists "order.t_order_detail"(
ROWKEY varchar primary key, 
"info"."order_id" varchar,
"info"."user_id" varchar,
"info"."gender" varchar,
"info"."real_name" varchar,
"info"."birthday" varchar,
"info"."idcard_up_pic" varchar,
"info"."idcard_down_pic" varchar,
"info"."certificate_face_pic" varchar,
"info"."head_pic" varchar,
"info"."ip" varchar,
"info"."gps" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."channel" varchar
);
create view if not exists "order.t_order_fee"(
ROWKEY varchar primary key, 
"info"."order_fee_id" varchar,
"info"."order_id" varchar,
"info"."fund_id" varchar,
"info"."fund_name" varchar,
"info"."fee_id" varchar,
"info"."company_id" varchar,
"info"."company_name" varchar,
"info"."company_type" varchar,
"info"."phase" varchar,
"info"."fee_rate" varchar,
"info"."total_fee" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."remark" varchar
);
create view if not exists "order.t_order_fee_detail"(
ROWKEY varchar primary key, 
"info"."detail_id" varchar,
"info"."order_id" varchar,
"info"."order_fee_id" varchar,
"info"."company_type" varchar,
"info"."fee_type" varchar,
"info"."fee_name" varchar,
"info"."fee_rate" varchar,
"info"."fee_rate_type" varchar,
"info"."coll_node" varchar,
"info"."fee_amount" varchar,
"info"."out_user_type" varchar,
"info"."out_user_id" varchar,
"info"."in_user_type" varchar,
"info"."in_user_id" varchar,
"info"."real_pay_time" varchar,
"info"."state" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."remark" varchar
);
create view if not exists "order.t_order_fee_v"(
ROWKEY varchar primary key,
);
create view if not exists "order.t_order_funding"(
ROWKEY varchar primary key, 
"info"."fund_id" varchar,
"info"."fund_name" varchar,
"info"."order_id" varchar,
"info"."user_id" varchar,
"info"."user_mobile" varchar,
"info"."real_name" varchar,
"info"."card_type" varchar,
"info"."card_no" varchar,
"info"."bank_mobile" varchar,
"info"."bank_no" varchar,
"info"."bank_name" varchar,
"info"."bank_fund_code" varchar,
"info"."bank_code" varchar,
"info"."bank_province_code" varchar,
"info"."bank_city_code" varchar,
"info"."remark" varchar,
"info"."valid" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar
);
create view if not exists "order.t_order_guarantee"(
ROWKEY varchar primary key, 
"info"."record_id" varchar,
"info"."order_id" varchar,
"info"."user_id" varchar,
"info"."fee" varchar,
"info"."status" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar,
"info"."timer" varchar,
"info"."result_desc" varchar,
"info"."remark" varchar,
"info"."creator" varchar,
"info"."editor" varchar,
"info"."type" varchar
);
create view if not exists "order.t_order_guarantee_audit"(
ROWKEY varchar primary key, 
"info"."record_id" varchar,
"info"."order_id" varchar,
"info"."order_no" varchar,
"info"."user_id" varchar,
"info"."mobile" varchar,
"info"."real_name" varchar,
"info"."amount" varchar,
"info"."phase" varchar,
"info"."status" varchar,
"info"."audit_type" varchar,
"info"."audit_time" varchar,
"info"."apply_time" varchar,
"info"."create_time" varchar,
"info"."edit_time" varchar,
"info"."creator" varchar,
"info"."editor" varchar,
"info"."remark" varchar,
"info"."stage" varchar
);
create view if not exists "order.t_order_record"(
ROWKEY varchar primary key, 
"info"."order_id" varchar,
"info"."fund_id" varchar,
"info"."order_type" varchar,
"info"."order_no" varchar,
"info"."order_property" varchar,
"info"."status_property" varchar,
"info"."status" varchar,
"info"."stage" varchar,
"info"."repay_model" varchar,
"info"."user_id" varchar,
"info"."user_mobile" varchar,
"info"."user_name" varchar,
"info"."order_amount" varchar,
"info"."total_rate" varchar,
"info"."total_fee" varchar,
"info"."order_rate" varchar,
"info"."fund_amount" varchar,
"info"."phase_total" varchar,
"info"."phase_mode" varchar,
"info"."risk_amount" varchar,
"info"."risk_phase" varchar,
"info"."risk_audit_time" varchar,
"info"."fund_audit_time" varchar,
"info"."fund_success_time" varchar,
"info"."rec_time" varchar,
"info"."withdraw_time" varchar,
"info"."chkout_time" varchar,
"info"."reject_time" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."remark" varchar,
"info"."purpose" varchar,
"info"."is_read" varchar
);
create view if not exists "order.t_order_record_log"(
ROWKEY varchar primary key, 
"info"."log_id" varchar,
"info"."order_id" varchar,
"info"."user_id" varchar,
"info"."status_property" varchar,
"info"."status" varchar,
"info"."stage" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."remark" varchar,
"info"."is_show" varchar,
"info"."description" varchar
);
create view if not exists "order.t_order_record_v"(
ROWKEY varchar primary key,
);
create view if not exists "order.t_repayment"(
ROWKEY varchar primary key, 
"info"."repayment_id" varchar,
"info"."user_id" varchar,
"info"."user_mobile" varchar,
"info"."order_id" varchar,
"info"."repay_model" varchar,
"info"."phase_total" varchar,
"info"."phase_mode" varchar,
"info"."phase" varchar,
"info"."expected_time" varchar,
"info"."expect_principal" varchar,
"info"."expect_fee" varchar,
"info"."expect_interest" varchar,
"info"."expect_fund_fee" varchar,
"info"."expect_platform_fee" varchar,
"info"."expect_ask_fee" varchar,
"info"."status" varchar,
"info"."actual_time" varchar,
"info"."actual_principal" varchar,
"info"."actual_fee" varchar,
"info"."overdue_fee" varchar,
"info"."overdue_rate" varchar,
"info"."clear_fee" varchar,
"info"."clear_rate" varchar,
"info"."properties" varchar,
"info"."actual_income" varchar,
"info"."fund_expected_time" varchar,
"info"."fund_actual_time" varchar,
"info"."fund_principal" varchar,
"info"."fund_interest" varchar,
"info"."fund_repay_fee" varchar,
"info"."fund_repay_id" varchar,
"info"."fund_amount" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."remark" varchar,
"info"."version" varchar,
"info"."channel" varchar
);
create view if not exists "order.t_repayment_log"(
ROWKEY varchar primary key, 
"info"."log_id" varchar,
"info"."repayment_id" varchar,
"info"."user_id" varchar,
"info"."order_id" varchar,
"info"."phase_total" varchar,
"info"."phase_mode" varchar,
"info"."phase" varchar,
"info"."expected_time" varchar,
"info"."expect_principal" varchar,
"info"."expect_fee" varchar,
"info"."status" varchar,
"info"."properties" varchar,
"info"."repay_result" varchar,
"info"."operation" varchar,
"info"."create_time" varchar,
"info"."remark" varchar
);
