create view if not exists "jld_funding.t_admin_log"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."operate_type_group" varchar,
"info"."operate_type" varchar,
"info"."operate_obj" varchar,
"info"."operator" varchar,
"info"."operate_time" varchar,
"info"."operate_detail" varchar,
"info"."remark" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_auth_log"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."record_id" varchar,
"info"."funding_channel" varchar,
"info"."auth_stage" varchar,
"info"."auth_status" varchar,
"info"."auth_result" varchar,
"info"."auth_result_code" varchar,
"info"."auth_result_msg" varchar,
"info"."request_type" varchar,
"info"."request_id" varchar,
"info"."request_url" varchar,
"info"."request" varchar,
"info"."response" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_auth_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."funding_channel_user_id" varchar,
"info"."user_id" varchar,
"info"."user_name" varchar,
"info"."mobile" varchar,
"info"."idcard_no" varchar,
"info"."bank_no" varchar,
"info"."bankcard_no" varchar,
"info"."bankcard_province" varchar,
"info"."bankcard_city" varchar,
"info"."auth_stage" varchar,
"info"."auth_status" varchar,
"info"."auth_result" varchar,
"info"."auth_result_code" varchar,
"info"."auth_result_msg" varchar,
"info"."version" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_funding_channel_info"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."channel_code" varchar,
"info"."channel_key" varchar,
"info"."channel_company_id" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."update_time" varchar,
"info"."updater" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_log"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."record_id" varchar,
"info"."funding_channel" varchar,
"info"."loan_id" varchar,
"info"."loan_stage" varchar,
"info"."loan_status" varchar,
"info"."loan_channel_status" varchar,
"info"."loan_result_code" varchar,
"info"."loan_result_msg" varchar,
"info"."request_type" varchar,
"info"."request_id" varchar,
"info"."request_url" varchar,
"info"."request" varchar,
"info"."response" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."user_id" varchar,
"info"."loan_id" varchar,
"info"."loan_stage" varchar,
"info"."loan_status" varchar,
"info"."loan_channel_status" varchar,
"info"."loan_result_code" varchar,
"info"."loan_result_msg" varchar,
"info"."loan_money" varchar,
"info"."loan_rate" varchar,
"info"."loan_phase" varchar,
"info"."loan_phase_mode" varchar,
"info"."loan_type" varchar,
"info"."loan_purpose" varchar,
"info"."loan_title" varchar,
"info"."loan_desc" varchar,
"info"."loan_user_career" varchar,
"info"."loan_user_salary" varchar,
"info"."repay_mode" varchar,
"info"."repaid_money" varchar,
"info"."repaid_phases" varchar,
"info"."version" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_repay_code"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."loan_id" varchar,
"info"."repay_type" varchar,
"info"."repay_phase" varchar,
"info"."repay_money" varchar,
"info"."repay_fee" varchar,
"info"."repay_code" varchar,
"info"."repay_code_reqid" varchar,
"info"."version" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_repay_log"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."record_id" varchar,
"info"."funding_channel" varchar,
"info"."loan_id" varchar,
"info"."request_type" varchar,
"info"."request_id" varchar,
"info"."request_url" varchar,
"info"."request" varchar,
"info"."response" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_repay_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."user_id" varchar,
"info"."loan_id" varchar,
"info"."repay_type" varchar,
"info"."repay_phase" varchar,
"info"."repay_money" varchar,
"info"."repay_fee" varchar,
"info"."repay_status" varchar,
"info"."repaid_time" varchar,
"info"."version" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_loan_time"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."loan_id" varchar,
"info"."time_init" varchar,
"info"."time_submit" varchar,
"info"."time_blackcheck" varchar,
"info"."time_material" varchar,
"info"."time_risk_audit" varchar,
"info"."time_market_audit" varchar,
"info"."time_fundraising" varchar,
"info"."time_release" varchar,
"info"."time_withdraw" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_mq_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."exchange_name" varchar,
"info"."msg_tag" varchar,
"info"."msg_content" varchar,
"info"."msg_sent_result" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_quota_conf"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."day_quota" varchar,
"info"."month_quota" varchar,
"info"."lending_time_start" varchar,
"info"."lending_time_end" varchar,
"info"."enabled" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."update_time" varchar,
"info"."updater" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_quota_consume_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."consume_year" varchar,
"info"."consume_month" varchar,
"info"."consume_day" varchar,
"info"."loan_id" varchar,
"info"."user_id" varchar,
"info"."push_req_id" varchar,
"info"."consume_amount" varchar,
"info"."consume_status" varchar,
"info"."day_quota" varchar,
"info"."month_quota" varchar,
"info"."day_quota_consumed" varchar,
"info"."month_quota_consumed" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_quota_consume_stat"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."consume_year" varchar,
"info"."consume_month" varchar,
"info"."consume_day" varchar,
"info"."day_quota" varchar,
"info"."month_quota" varchar,
"info"."day_quota_consumed" varchar,
"info"."month_quota_consumed" varchar,
"info"."version" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_routing_conf"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."priority" varchar,
"info"."fee_rate" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."update_time" varchar,
"info"."updater" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_sign_log"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."record_id" varchar,
"info"."funding_channel" varchar,
"info"."sign_status" varchar,
"info"."request_type" varchar,
"info"."request_id" varchar,
"info"."request_url" varchar,
"info"."request" varchar,
"info"."response" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."deleted" varchar
);
create view if not exists "jld_funding.t_sign_record"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."funding_channel" varchar,
"info"."user_id" varchar,
"info"."sign_status" varchar,
"info"."sign_request_cnt" varchar,
"info"."last_request_sign_time" varchar,
"info"."version" varchar,
"info"."remark" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."deleted" varchar
);
