create view if not exists "asset.t_attachment"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."file_name" varchar,
"info"."file_type" varchar,
"info"."file_size" varchar,
"info"."file_url" varchar,
"info"."remarks" varchar,
"info"."create_time" varchar,
"info"."create_user" varchar
);
create view if not exists "asset.t_bank_config"(
ROWKEY varchar primary key, 
"info"."id" varchar,
"info"."org_from_id" varchar,
"info"."org_from_name" varchar,
"info"."org_from_type" varchar,
"info"."org_to_id" varchar,
"info"."org_to_name" varchar,
"info"."org_to_type" varchar,
"info"."bank_from_name" varchar,
"info"."bank_from_code" varchar,
"info"."bank_to_name" varchar,
"info"."bank_to_code" varchar,
"info"."bank_from_icon" varchar,
"info"."bank_from_sort" varchar,
"info"."bank_from_recom" varchar,
"info"."from_sigle_limit" varchar,
"info"."from_day_limit" varchar,
"info"."from_month_limit" varchar,
"info"."bank_from_open" varchar,
"info"."create_time" varchar,
"info"."update_time" varchar,
"info"."create_by" varchar,
"info"."update_by" varchar
);
create view if not exists "asset.t_cooperation"(
ROWKEY varchar primary key, 
"info"."company_id" varchar,
"info"."company_name" varchar,
"info"."company_type" varchar,
"info"."register_name" varchar,
"info"."register_mobile" varchar,
"info"."user_id" varchar,
"info"."register_idcard" varchar,
"info"."bank_account_name" varchar,
"info"."bank_account_id" varchar,
"info"."artif_name" varchar,
"info"."bank_province_id" varchar,
"info"."bank_city_id" varchar,
"info"."bank_code" varchar,
"info"."email" varchar,
"info"."company_desc" varchar,
"info"."update_time" varchar,
"info"."create_time" varchar,
"info"."business_license_no" varchar,
"info"."tax_no" varchar,
"info"."organization_code" varchar,
"info"."social_credit_code" varchar,
"info"."account_type" varchar,
"info"."account_type_desc" varchar,
"info"."creator" varchar,
"info"."updator" varchar,
"info"."remark" varchar,
"info"."disable" varchar,
"info"."state" varchar
);
create view if not exists "asset.t_product_fee"(
ROWKEY varchar primary key, 
"info"."fee_id" varchar,
"info"."fee_name" varchar,
"info"."company_id" varchar,
"info"."company_name" varchar,
"info"."company_type" varchar,
"info"."phase" varchar,
"info"."fee_rate" varchar,
"info"."state" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."update_time" varchar,
"info"."updator" varchar,
"info"."remark" varchar,
"info"."disable" varchar
);
create view if not exists "asset.t_product_fee_detail"(
ROWKEY varchar primary key, 
"info"."detail_id" varchar,
"info"."fee_id" varchar,
"info"."company_type" varchar,
"info"."fee_type" varchar,
"info"."fee_name" varchar,
"info"."fee_rate" varchar,
"info"."fee_rate_type" varchar,
"info"."coll_node" varchar,
"info"."inner_type" varchar,
"info"."out_user_type" varchar,
"info"."out_user_id" varchar,
"info"."in_user_type" varchar,
"info"."in_user_id" varchar,
"info"."create_time" varchar,
"info"."creator" varchar,
"info"."update_time" varchar,
"info"."updator" varchar,
"info"."remark" varchar,
"info"."disable" varchar
);
create view if not exists "asset.t_region"(
ROWKEY varchar primary key, 
"info"."region_id" varchar,
"info"."region_code" varchar,
"info"."region_name" varchar,
"info"."PARENT_id" varchar,
"info"."region_level" varchar,
"info"."region_order" varchar,
"info"."region_name_en" varchar,
"info"."region_shortname_en" varchar
);
